# Configuração básica para GitHub Pages + Minimal Mistakes
title: "Meus Writeups CTF"
description: "Writeups de HTB, CTFs e notas técnicas"
url: "https://kelme108.github.io"
baseurl: "/teste-writeups"   # nome exato do repositório
remote_theme: "mmistakes/minimal-mistakes"

# Opções úteis
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Dados do autor (opcional)
author:
  name: "Kelme108"
  avatar: "{{ site.baseurl }}/assets/img/exemplo.png"
  bio: "Pentester / CTF enthusiast"

# Exibir opções de navegação (ver docs do tema para customização)
navigation:
  - title: "Home"
    url: "{{ site.baseurl }}/"
  - title: "Writeups"
    url: "{{ site.baseurl }}/posts/"

# Ajustes de sintaxe de código
markdown: kramdown

